### PR TITLE
added raw csv files (output of to_csv.py)

### PR DESCRIPTION
**Pull request by Bibiko**

### CODE REVIEW

**Review by xrotwang — APPROVED** [review]
Looks good. Maybe turning holders into `Contributor`s and all sticks from the same holder into `ValueSet`s of one `Contribution` would make sense? Linguistic areas would then best map to `Language` - although, IIRC there are some sticks related to more than one area - but this could be added as additional relation to a custom `ValueSet` derivation.

**Comment by Bibiko** [comment]
"turning holders into Contributors and all sticks from the same holder into ValueSets of one Contribution" - ok, this would be done in to_cldf.py - regarding ling_area, well, 15 areas have no glottolog code, and afaik these info are a bit vague

**Comment by xrotwang** [comment]
A `Language` isn't required to have a glottocode. In fact it, isn't required to be anything language like at all. In the D-PLACE app, societies are modelled as `Language`. And considering that "linguistic areas" are the only thing in AMSD we might want to put on a map, modelling them as `Language` seems appropriate.

**Comment by xrotwang** [comment]
Btw. `to_cldf.py` would be a bit of a misnomer, right? I can't see what kind of CLDF dataset this could be turned into.

**Comment by Bibiko** [comment]
re Language: ok, re to_cldf: ok, I could write initialised.py in such a way to use the raw/*.csv directly

**Pull request merged**
